spring:
    application:
        name: countries-app-sample
server:
    port: 8084
logging:
    level:
        com.github: DEBUG
    pattern:
        console: "[%d{yyyy-MM-dd HH:mm:ss}]: %m%n"
    file: countries.log