sudo: false
dist: trusty
install: true

addons:
  sonarcloud:
    organization: "noraui"

matrix:
  include:
  - language: java
    jdk: oraclejdk8
    before_install:
      - chmod +x test/runBackend.sh
      - chmod +x test/after_success.sh
    script:
      - test/runBackend.sh
    after_success: 
      - test/after_success.sh  
    cache:
      directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'  

  - language: node_js
    node_js: 8.1.3
    before_install:
      - chmod +x test/runFrontend.sh
    script:
      - test/runFrontend.sh
