language: java
sudo: false
dist: trusty
install: true

jdk:
- oraclejdk8

before_install:
- chmod +x test/run.sh

script:
- test/run.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'